local imageFolder = "Interface\\AddOns\\SlashikRaidBreakTime\\images\\"

SlashikRaidBreakTimeImages = {
    imageFolder = imageFolder,
    "eilee-break.tga",
    "slashik-break.tga",
    "whjinsck-break.tga",
    "frosham-break.tga",
    "skautik-break.tga",
    "skautik-masterpiece-break.tga",
    "nadytaur-break.tga",
    "dengske-break.tga",
    "hoofski-break.tga",
    "olodos-break.tga",
    "thebringer-break.tga",
    "alghol-break.tga",
    "innerdrive-break.tga",
    "kyubiistraza-break.tga",
    "critcat-break.tga",
    "genohacker-break.tga",
    "varanus-break.tga",
    "chickenwing-break.tga",
    "padonk-break.tga",
    "wixxie-break.tga",
    "shocktopuss-break.tga",
    "miztaxih-break.tga",
}
