local events = CreateFrame("Frame")
events:RegisterEvent("PLAYER_LOGIN")
events:SetScript("OnEvent", function()
    local button = CreateFrame("Button", "SlashikRaidBreakTimeMinimapButton", Minimap)
    button:SetSize(32, 32)
    button:SetFrameStrata("MEDIUM")
    button:SetFrameLevel(Minimap:GetFrameLevel() + 5)
    button:RegisterForClicks("LeftButtonUp", "RightButtonUp")
    button:RegisterForDrag("LeftButton")
    local icon = button:CreateTexture(nil, "BACKGROUND")
    icon:SetTexture("Interface\\AddOns\\SlashikRaidBreakTime\\addonIcon")
    icon:SetSize(22, 22)
    icon:SetPoint("CENTER")
    local border = button:CreateTexture(nil, "OVERLAY")
    border:SetTexture("Interface\\Minimap\\MiniMap-TrackingBorder")
    border:SetSize(54, 54)
    border:SetPoint("TOPLEFT")
    button:SetHighlightTexture("Interface\\Minimap\\UI-Minimap-ZoomButton-Highlight")
    local function position(angle)
        local radius = math.max(Minimap:GetWidth(), Minimap:GetHeight()) / 2 + 8
        button:ClearAllPoints()
        button:SetPoint("CENTER", Minimap, "CENTER", math.cos(angle) * radius, math.sin(angle) * radius)
    end
    local angle = getSettings().minimapAngle
    position(type(angle) == "number" and angle or math.rad(220))
    button:SetScript("OnDragStart", function(self)
        self:SetScript("OnUpdate", function()
            local x, y = GetCursorPosition()
            local cx, cy = Minimap:GetCenter()
            local scale = Minimap:GetEffectiveScale()
            local radians = math.atan2(y / scale - cy, x / scale - cx)
            getSettings().minimapAngle = radians
            position(radians)
        end)
    end)
    button:SetScript("OnDragStop", function(self) self:SetScript("OnUpdate", nil) end)
    button:SetScript("OnClick", function(_, mouse)
        if mouse == "LeftButton" then
            showRaidBreakPartyKeystones()
        elseif mouse == "RightButton" then
            showRaidBreakAddonSettings()
        end
    end)
    button:SetScript("OnEnter", function(self)
        GameTooltip:SetOwner(self, "ANCHOR_LEFT")
        GameTooltip:SetText("Slashik Raid Break Time")
        GameTooltip:AddLine("Left-click: party keystones", 1, 1, 1)
        GameTooltip:AddLine("Right-click: module settings", 1, 1, 1)
        GameTooltip:AddLine("Left-drag: move around the minimap", 1, 1, 1)
        GameTooltip:Show()
    end)
    button:SetScript("OnLeave", function() GameTooltip:Hide() end)
end)
